Feature: 背景の画像たちにアニメーションを付ける
Ixy194194/ixy194194.github.io pull request #20
Opened 2023-03-25 23:21 UTC by Fairy-Phy

## 概要

Gridで画像一覧のように表示しているのが寂しく感じたので背景の画像たちにアニメーションを付けました。

* 変更前
![image](https://user-images.githubusercontent.com/48243496/227746638-93330487-7d50-47f6-966e-d23c943b4228.png)
* 変更後
![image](https://user-images.githubusercontent.com/48243496/227746680-5c6df41f-9a67-479c-bb4c-46994f99c3b4.png)

## 内容

* 画像をランダムにシャッフルし、表示する
* 列を横に移動するアニメーションを追加
* 横に移動した際に新たにシャッフルされた画像群がアニメーションで表示される
* 画面の高さに応じて列が追加される
* 奇数列はアニメーションが逆になる

## その他・特記事項

* `next export`時に`api`フォルダー内にファイルが存在することで生じるwarnを解消するために`api/hello.ts`を削除しました。

↓`next export`時に出たwarn
![image](https://user-images.githubusercontent.com/48243496/227746579-6cc73ba6-4f5f-446c-b580-dc3d842ab28a.png)

* 初めてReactベースのフレームワークを使ったのでコードの不備がありましたらコメントください...

2023-03-26 02:28 UTC, CookieRamen requested changes
概ね大丈夫ですが、一部インデントがおかしい部分があるので修正していただけると・・・！

面倒であればこちらでマージ後修正も可能です。

2023-03-26 02:28 UTC, CookieRamen commented on components/imagecard/ImageLine.tsx
> +		<div className="absolute flex gap-12 opacity-25 px-6 py-8 image-line-anim">
何故かインデントがTabになっている

2023-03-26 04:10 UTC, ysknsid25 commented
@Fairy-Phy 

横からすみません…！
自分の方で先にテストコードを追加したプルリクがdevブランチにマージされておりまして、
おそらく今のままマージしてしまうとGithub Actionsのワークフローでユニットテストがこけてしまいます。

なので、一度upstreamのdevブランチから最新ソースを取得したうえで、しせるさんのimage-card-animateブランチにマージしていただいて、テストコードまで書いていただけますと助かります。

大変お手数ですが何卒よろしくお願いいたします🙏

2023-03-26 04:13 UTC, Fairy-Phy commented
@ysknsid25 わかりました！そこも修正しますね...

2023-03-26 04:21 UTC, ysknsid25 commented
@Fairy-Phy 

本当に申し訳ないです😭😭😭
よろしくお願いいたします🙇

(どうでもいいのですが、しせるさんのアイコンがめちゃくちゃ可愛くてきゅんです)

2023-03-26 04:23 UTC, ysknsid25 commented
あと独り言なのですが、github pagesってプルリク出した時点のソースで
本番に影響がない形でデプロイして動作確認ってできなかったでしたっけ…？
(Firebase Hostingはそんなことができた覚えがある)

というのは、自分やせしるさんみたいに修正時に毎回画像貼るのがめんどくさいというだけなんですけどね…

2023-03-26 04:30 UTC, ysknsid25 commented
あと独り言なのですが、github pagesってプルリク出した時点のソースで
本番に影響がない形でデプロイして動作確認ってできなかったでしたっけ…？
(Firebase Hostingはそんなことができた覚えがある)

というのは、自分やせしるさんみたいに修正時に毎回画像貼るのがめんどくさいというだけなんですけどね…

↓

できそうですけど、若干めんどくさそう
https://miraitranslate-tech.hatenablog.jp/entry/2021/12/24/120000

2023-03-26 04:35 UTC, Fairy-Phy commented
> あと独り言なのですが、github pagesってプルリク出した時点のソースで 本番に影響がない形でデプロイして動作確認ってできなかったでしたっけ…？ (Firebase Hostingはそんなことができた覚えがある)
> 
> というのは、自分やせしるさんみたいに修正時に毎回画像貼るのがめんどくさいというだけなんですけどね…
> 
> ↓
> 
> できそうですけど、若干めんどくさそう https://miraitranslate-tech.hatenablog.jp/entry/2021/12/24/120000

単純にGithubActionをフォーク先でも割り当てれば行けそう？(適当)

2023-03-26 04:42 UTC, ysknsid25 commented
> 単純にGithubActionをフォーク先でも割り当てれば行けそう？(適当)

なーるほど
自分が見るだけならそれでできそうですね👀

このリポジトリを見に来た人全員が、他人のプルリクに対してもデプロイされた修正分の環境を見れる感じにしておくと、
レビュワーの目が多くなって、それはそれでOSSっぽいと思ったんですけどね

2023-03-26 05:20 UTC, CookieRamen commented
一応将来的にはドメインを取る感じなので、その際にCloudFlare Pagesに移行してPR環境のプレビューなどもできるようにしようと考えています。

2023-03-26 06:18 UTC, Fairy-Phy commented
@ysknsid25 @CookieRamen 
同期+追加しました～

~~(テストケースを考えようとしたけどそもそもアニメーションとかランダム要素含むものってできないじゃんって思った)~~

2023-03-26 06:24 UTC, ysknsid25 commented
> @ysknsid25 @CookieRamen 同期+追加しました～
> 
> ~(テストケースを考えようとしたけどそもそもアニメーションとかランダム要素含むものってできないじゃんって思った)~

@Fairy-Phy 

ありがとうございます！

> ~(テストケースを考えようとしたけどそもそもアニメーションとかランダム要素含むものってできないじゃんって思った)~

~それもあるので、プレビュー環境ほしいなぁという独り言でした💦~

2023-03-26 06:54 UTC, Ixy194194 commented
寝てる間にすごいことに！ありがとうございます～！

2023-03-26 06:56 UTC, ysknsid25 commented
@Ixy194194 

先生とリアル なれるSE できてめちゃくちゃ楽しいです😆

2023-03-26 14:50 UTC, Fairy-Phy commented
見直したらすごく細かいところに気づいてしまったので修正しました...
よろしくお願いします

2023-03-26 17:38 UTC, CookieRamen approved these changes

2023-03-26 17:39 UTC, merged

2023-03-28 06:28 UTC, CookieRamen commented
@Fairy-Phy マージ後でアレですけど、結構思いのでCSSで書き直してPR立ててくれると助かるかも

2023-03-28 09:31 UTC, Fairy-Phy commented
@CookieRamen すいません...一応聞いておきたいのですがどう重いとかありますか？(コードの問題なのかライブラリの問題なのかの確認のため)